### PR TITLE
Fix PE parsing of VersionString

### PR DESCRIPTION
**Pull request by carlbennett**
Attempts to resolve issue #6: Fix PE parsing of VersionString

Author: @CHOB-HET | Committer: @carlbennett

### CODE REVIEW

**Comment by CHOB-HET** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms680341(v=vs.85).aspx

> Name: An 8-byte, null-padded UTF-8 string. There is no terminating null character if the string is exactly eight characters long.

maybe need change
**_if(strcmp(sect->name,".rsrc")==0)_**
to
**_if(strncmp(sect->name,".rsrc",8)==0)_**
but ".rsrc" has 5 byte lenght and always 0-terminated, so 8 byte length for name is unreachable

**Comment by inetknght** [comment]
@CHOB-HET neat utility to confirm what you think about 8-byte length being unreachable; `-O3` in GCC, the compiler will use the exact same instruction anyway (`repz cmpsb`). Compare an [excerpt of 1d8a9f6](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZTUAHAvVAOwGdK0AbVAV2J4OmAIIcAtiADkABmmk0Exnh6YA8mwDCCAIZtgmGfICUpDgOLIj0gKSzRtgEwBmPG2Q9%2BWANS2XWsgcBPhsBP7Y9o6u7p7emH4BQSGsEVHObh5evv6BwUIGaQ5RBACejJhYAGY%2B%2BfzIBD7IEgD6FS0ImLpYxH4A7ABCUT4jPvzuBC5OLY0ceMBsugSCmP5DDqNjE7QAbDM%2BErrICO6rLgObl1eXAPQ3PgCSALKiAOLYLQBiDwAyHy9aAASDwAch8AFTDUbjMK7fYiBqsNgtND8MJrKEjGGTaaNFgSTDBXTKDEbaETKbw0oSABGqB4M10NLULVQVSqInC50xWzClNm1LpDNR6O5ZKx2z2jSYLHYugZnW6mGILTmAC8zutRJtsXDGsddMQjgRlcIWEFSY4%2BgARJqtdqKnozS0lcqVTA1OoNO1tTCs5hI%2BUdLo9fpanWS/aHYB4ZBra4JxN3Hx4aMJKokQ6NCAABWwUxueamzgGJh52IAHFHdFQSC0eO4ANbKloAN2Vc3YlojYSrjQk7jrDbYzZV7eInbY3fJfNxTQwfoRsuR6s15Ypc/chDw8rwGvQLXQS10qr3a/FvJx%2BzRW5Yu/3h%2BPp4104ls/2mDCxFKbVQE1fl78vOWAtDSugiAB2JAUeBAnmBEHnImSE%2BMmbCoI0jDEISn6NO4PhFk4JZgGA6Q2j67QyoGCohi2XJaukrjVKc%2BEfOoOYACoPOoIKiD8LSAtgojWtgABKLRPKCLQAMoPAAWtgPgQKubIQM0vr%2BsuQaOrRJg%2BAAtD4AAsZbFA4ZQVNUtQEMQ9T6vafoAO7uOgqAORwwZKr0tiDOuYQ7IZ%2ByprohigeB57ajOV6zJgiLsC0u4LASorhpFQFVKofoJWwSV0b5BB6gcNZ1qg7njpOkGRv2g4qiVbYdkiFWwlKhW1iqQUhWVDVihFb75c1A5oW1aZ1ROXUpb1BWHK1qr8DSHClMEmCtJ1XbdT2fVRtVM1zQtJrLfVq3jYBc5YSIxDtugjVRSmw2rldQHaROz7hetQHHDFjYcPwEhXQVX07YtP1rZFBXoDwwp6EaDSmsEsYcFd/nwrByCNi0p3Ku2z0IwFszI6jSgDgQWPA71iONIqjBo9h52Lme2P7BTKKoBIhPE0dUFznwnktFUPDBfDJPHfsMEnvgWENCQP4irlxRkWp7ROWwLluR5Toy44ZlupZXp2epIuHng4tEN%2BYZ5UB526Pdc53d13m2vLfr62LMXGz%2B6uuhZHpWTZ3oO6qLtIqbF4Gr0iwErYACsAwVpH1pW/sraG8sQY2%2BzG4J0n/BBt06CnQLafvo0RoOY%2BsFs2bJ26CX%2BtshymDq69J2YHwyBLEi7m15y8eNMOfpsN9NIdqy7Jd4LurNVhLdt3F0u/c1vctP3tItrPY/p/qkPGjD5r56R9v2f7sXIu7mue561m2eRCTeUd3x/OCPhVABfuPQzNHEM/B%2BUXK1Hc9KAY/1VsqT%2B6lFbK3cq/RoYDXIQPfiA9oTtDYu0ljMB%2BiCjYkDwISeBi4A5xQIA/Jc7cXRkXBH7E%2BogJhXx5ngAAHpUEak4WiYFodYYgzBVIHwwpgEyVojrJnSkrPwTgnAADoJxWGcE4WoeCpzBwPkQ/BhCXaJFtBUPSERFGcAAjfHkmwqF4FICJDgVhPgCCEf4W0sgAKbAzMQCAeBLHWMQo4gI6iIiPVEVopmaI6IphLCWXhCZdEXgTHgKoSlrLNEYEpF2GiXDYDDpgUgUjxEmLjCIssLg47ZNkEE5CISerIRGMY0x5j0CqJ8LQGxyEaRYV0I2GpVw7Z6OuEuYRQxslVKaf0OOoTRjhIgKU5AZi0SXWyU43SqFUA%2BFOpYawHBEifH8Mslwyz%2BlXCwssYgbAfDOKOi0i8WzBC7OqbbG0URpBmB4DICOCg2AyFoAoVAMgtABKcBcCwghrDCJcE80gBBjBXLMI2EAEdZCkBudIQy9ygUMBkAoLgELAVyCuaQOAsAkBKBUGoMgFBVLMxxcqEAwAdhOFIOlHgJoJyUBpHCgmOFNA8FKHC52iJ2xcFReQMIzcgVmG/pwGQel1AuDRVCu5pAHlcpeXYVwtAfBOQIAgHwtCKw7D0v5HwwBkDIB8DsURTgFAotMCCsFEKoUwslXCmViKQDIr5dcmQhqrXSoRQCh1pAVoPMMkAA%3D%3D) against [the same excerpt but with `strncmp`](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZTUAHAvVAOwGdK0AbVAV2J4OmAIIcAtiADkABmmk0Exnh6YA8mwDCCAIZtgmGfICUpDgOLIj0gKSzRtgEwBmPG2Q9%2BWANS2XWsgcBPhsBP7Y9o6u7p7emH4BQSGsEVHObh5evv6BwUIGaQ5RBACejJhYAGY%2B%2BfzIBD7IEgD6FS0ImLpYxH4A7ABCUT4jPvzuBC5OLY0ceMBsugSCmP5DDqNjE7QAbDM%2BErrICO6rLgObl1eXAPQ3PgCSALKiAOLYLQBiDwAyHy9aAASDwAch8AFTDUbjMK7fYiBqsNgtND8MJrKEjGGTaaNFgSTDBXTKDEbaETKbw0oSABGqB4M10NLULVQVSqInC50xWzClNm1LpDNR6O5ZKx2z2jSYLHYugZnW6mGILTmAC8zutRJtsXDGsddMQjgRlcIWEFSY4%2BgARJqtdqKnozS0lcqVTA1OoNO1tTCs5hI%2BUdLo9fpanWS/aHYB4ZBra4JxN3Hx4aMJKokQ6NCAABWwUxueamzgGJh52IAHFHdFQSC0eO4ANbKloAN2Vc3YlojYSrjQk7jrDbYzZV7eInbY3fJfNxTQwfoRsuR6s15Ypc/chDw8rwGvQLXQS10qr3a/FvJx%2BzRW5Yu/3h%2BPp4104ls/2mDCxFKbVQE1fl78vOWAtDSugiAB2JAUeBAnmBEHnImSE%2BMmbCoI0jDEISn6NO4PhFk4JZgGA6Q2j67QyoGCohi2XJaukrjVKc%2BEfOoOYACoPOoIKiD8LSAtgojWtgABKLRPKCLQAMoPAAWtgPgQKubIQM0vr%2BsuQaOrRJg%2BAAtD4AAsZbFA4ZQVNUtQEMQ9T6vafoAO7uOgqAORwwZKr0tiDOuYQ7IZ%2ByprohigeB57ajOV6zJgiLsC0u4LASorhpFQFVKofoJWwSV0b5BB6gcNZ1qg7njpOkGRv2g4qiVbYdkiFWwlKhW1iqQUhWVDVihFb75c1A5oW1aZ1ROXUpb1BWHK1qr8DSHClMEmCtJ1XbdT2fVRtVM1zQtJrLfVq3jYBc5YSIxDtugjVRSmw2rldQHaROz7hetQHHDFjYcPwEhXQVX07YtP1rZFBXoDwwp6EaDSmsEsYcFd/nwrByCNi0p3Ku2z0IwFszI6jSgDgQWPA71iONIqjBo9h52Lme2P7BTKKoBIhPE0dUFznwnktFUPDBfDJPHfsMEnvgWENCQP4irlxRkWp7ROWwLluR5Toy44ZlupZXp2epIuHng4tEN%2BYZ5UB526Pdc53d13m2vLfr62LMXGz%2B6uuhZHpWTZ3oO6qLtIqbF4Gr0iwErYACsAwVpH1pW/sraG8sQY2%2BzG4J0n/BBt06CnQLafvo0RoOY%2BsFs2bJ26CX%2BtshymDq69J2YHwyBLEi7m15y8eNMOfpsN9NIdqy7Jd4LurNVhLdt3F0u/c1vctP3tItrPY/p/qkPGjD5r56R9v2f7sXIu7mue561m2eRCTeUd3x/OCPhVABfuPQzNHEM/B%2BUXK1Hc9KAY/1VsqT%2B6lFbK3cq/RoYDXIQPfiA9oTtDYu0ljMB%2BiCjYkDwISeBi4A5xQIA/Jc7cXRkXBH7E%2BogJhXx5ngAAHpUEak4WiYFodYYgzBVIHwwpgEyVojrJnSkrPwTgnAADoJxWGcE4WoeCpzBwPkQ/BhCXaJFtBUPSERFGcAAjfHkmwqF4FICJDgVhPgCCEf4W0sgAKbAzMQCAeBLHWMQo4gI6iIiPVEVopmaI6IphLCWXhCZdEXgTHgKoSlrIeGUEpF2GiXDYDDpgUgUjxEmLjCI8wZ4VJLniYk4kPCywuDjsU2QQTkIhJ6shEYxjTHmPQKonwtAbHIRpFhXQjYWlXDtno64S5hFDGKU0rp/Q46hNGOEiAtTkBmLRJdYpTjdKoVQD4U6lhrAcESJ8fw2yXDbPGVcLCyxiBsB8M4o6PSLxHMEKc5ptsbRRGkGYHgMgI4KDYDIWgChUAyC0AEpwFwLCCGsMIlwXzSAEGME8swjYQAR1kKQF50hDLvKhQwGQCguAIshXIJ5pA4CwCQEoFQagyAUFUszElyoQDAB2E4Ug6UeAmgnJQGkaKCY4U0DwUoaLnaInbFwXF5AwjNyhWYb%2BnAZB6XUC4PFSK3mkA%2BUKn5dhXC0B8E5AgCAfC0IrDsPS/kfDAGQMgHwOxRFOAUDi0wMK4UIqRSixVaKVWYpANisVzyZCWqdcqjFEKPWkBWh8wyQA).

@carlbennett I think a better thing would be to remove the `RsrcFound` variable as it is unnecessary. It can be rolled into `i` variable. Consider [this](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZTUAHAvVAOwGdK0AbVAV2J4OmAIIcAtiADkABmmk0Exnh6YA8mwDCCAIZtgmGfICUpDgOLIj0gKSzRtgEwBmPG2Q9%2BWANS2XWsgcBPhsBP7Y9o6u7p7emH4BQSGsEVHObh5evv6BwUIGaQ5RBACejJhYAGY%2B%2BfzIBD7IEgD6FS0ImLpYxH4A7ABCUT4jPvzuBC5OLY0ceMBsugSCmP5DDqNjE7QAbDM%2BErrICO6rLgObl1eXAPQ3PgCSALKiAOLYLQBiDwAyHy9aAASDwAch8AFTDUbjMK7fYiBqsNgtND8MJrKEjGGTaaNFgSTDBXTKDEbaETKbw0oSABGqB4M10NLULVQVSqInC50xWzClNm1LpDNR6O5ZKx2z2jSYLHYugZnW6mGILTmAC8zutRJtsXDGsddMQjgRlcIWEFSY4%2BgARJqtdqKnozS0lcqVTA1OoNO1tTCs5hI%2BUdLo9fpanWS/aHYB4ZBra4JxN3Hx4aMJKokQ6NCAABWwUxueamzgGJh52IAHFHdFQSC0eO4ANbKloAN2Vc3YlojYSrjQk7jrDbYzZV7eInbY3fJfNxTQwfoRsuR6s15Ypc/chDw8rwGvQLXQS10qr3a/FvJx%2BzRW5Yu/3h%2BPp4104ls/2mDCxFKbVQE1fl78vOWAtDSugiAB2JAUeBAnmBEHnImSE%2BMmbCoI0jDEISn6NO4PhFk4JZgGA6Q2j67QyoGCohi2XJaukrjVKc%2BEfOoOYACoPOoIKiD8LSAtgojWtgABKLRPKCLQAMoPAAWtgPgQKubIQM0vr%2BsuQaOrRJg%2BAAtD4AAsZbFA4ZQVNUtQEMQ9T6vafoAO7uOgqAORwwZKr0tiDOuYQ7IZ%2ByprohigeB57ajOV6zJgiLsC0u4LASorhpFQFVKofoJWwSV0b5BB6gcNZ1qg7njpOkGRv2g4qiVbYdkiFWwlKhW1iqQUhWVDVihFb75c1A5oW1aZ1ROXUpb1BWHK1qr8DSHClMEmCtJ1XbdT2fVRtVM1zQtJrLfVq3jYBc5YSIxDtugjVRSmw2rldQHaROz7hetQHHDFjYcPwEhXQVX07YtP1rZFBXoDwwp6EaDSmsEsYcFd/nwrByCNi0p3Ku2z0IwFszI6jSgDgQWPA71iONIqjBo9h52Lme2P7BTKKoBIhPE0dUFznwnktFUPDBfDJPHfsMEnvgWENCQP4irlxRkWp7ROWwLluR5Toy44ZlupZXp2epIuHng4tEN%2BYZ5UB526Pdc53d13m2vLfr62LMXGz%2B6uuhZHpWTZ3oO6qLtIqbF4Gr0iwErYACsAwVpH1pW/sraG8sQY2%2BzG4J0n/BBt06CnQLafvo0RoOY%2BsFs2bJ26CX%2BtshymDq69J2YHwyBLEi7m15y8eNMOfpsN9NIdqy7Jd4LurNVhLdt3F0u/c1vctP3tItrPY/p/qkPGjD5r56R9v2f7sXIu7mue561m2eRCTeUd3x/OCPhVABfuPQzNHEM/B%2BUXK1Hc9KAY/1VsqT%2B6lFbK3cq/RoYDXIQPfiA9oTtDYu0ljMB%2BiCjYkDwISeBi4A5xQIA/Jc7cXRkXBH7E%2BogJhXx5ngAAHpUEak4WiYFodYYgzBVIHwwpgEyVojrJnSkrPwTgnAADoJxWGcE4WoeCpzBwPkQ/BhCXaJFtBUPSERFGcAAjfHkmwqF4H8NaWQAFNgZmIBAeMhiAjqIiI9URWimZojosIoYTgBh4F4QmXRF4Ex4CqEpayHhlBKRdpHDxsdRFh0wKQKR4iOCSJEeYM8KklzhMMRHa0UTiQ8LLC4OO%2BTZBeOQj4nqyERhLlUcInYaSo4ZIKUdcpNIsK6EbKY64ds9GjE6b40Y/iIB4FUUYnwtiXDYHsY46WulUKoB8KdSw1gOCJE%2BP4FZLgVm9KuFhZYxA2A%2BBMYLHpZTtmCD2bQEhccHDSDMDwGQEcFBsBkLQBQqAZBaBLCWWoCzr6uGeaQAgxhrlmEbCACOshSC3OkIZB5gKGAyAUFwcFAK5DXNIHAWASAlAqDUGQCgqlmbYuVCAYAOwnCkHSjwE0E5KA0lhQTHCmgeClFhc7RE7YuAovIGEZugKzDf04DIPS6gXCoshfc0gjzOWvLsL8nwTkCAIB8LQisOw9L%2BR8MAZAyAfA7FEU4BQyLTDAtBeCyF0KJWwulQikASLeU3JkPqi1Ur4X/LtaQFajzDJAA%3D%3D); I believe this better describes _intent_ to the compiler.

**Comment by carlbennett** [comment]
@CHOB-HET @inetknght @cen1 - I've committed up the latest code review suggestions, needs retest please!

**Comment by carlbennett** [comment]
It built for me on `4.7.5-200.fc24.x86_64` with `gcc version 6.2.1 20160916 (Red Hat 6.2.1-2) (GCC)`

[build.txt](https://github.com/BNETDocs/bncsutil/files/533820/build.txt)

**Comment by CHOB-HET** [comment]
all ok, go go host on eurobatlle.net and iccup

**Pull request merged**
